
create table if not exists quote_counter (
  year int primary key,
  next_number int not null default 1
);

create or replace function next_quote_number()
returns text
language plpgsql
as $$
declare
  y int := extract(year from now())::int;
  n int;
begin
  insert into quote_counter(year, next_number)
  values (y, 2)
  on conflict (year)
  do update set next_number = quote_counter.next_number + 1
  returning next_number - 1 into n;

  if n is null then n := 1; end if;
  return 'CIC-' || y || '-' || lpad(n::text, 4, '0');
end;
$$;

create table if not exists quotes (
  quote_no text primary key,
  customer text,
  customer_type text,
  status text,
  lines jsonb,
  totals jsonb,
  created_by text,
  created_at timestamptz default now()
);

create table if not exists purchase_orders (
  po_no text primary key,
  quote_no text references quotes(quote_no) on delete cascade,
  supplier text,
  status text,
  lines jsonb,
  totals jsonb,
  created_by text,
  created_at timestamptz default now()
);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text unique not null,
  type text default 'standard',
  email text,
  phone text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists app_settings (
  id int primary key,
  settings jsonb
);

alter table quotes enable row level security;
alter table purchase_orders enable row level security;
alter table customers enable row level security;
alter table app_settings enable row level security;
alter table quote_counter enable row level security;

create policy "quotes auth all" on quotes for all to authenticated using (true) with check (true);
create policy "po auth all" on purchase_orders for all to authenticated using (true) with check (true);
create policy "customers auth all" on customers for all to authenticated using (true) with check (true);
create policy "settings auth all" on app_settings for all to authenticated using (true) with check (true);
create policy "counter auth all" on quote_counter for all to authenticated using (true) with check (true);

insert into app_settings(id, settings)
values (1, '{"markup":20,"guernseyShipping":15.7,"repeatDiscount":5,"tradeDiscount":10,"minMargin":12}')
on conflict (id) do nothing;
